# Generated by Django 3.1.2 on 2020-10-28 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('owner', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(max_length=200)),
                ('firstName', models.TextField(max_length=200)),
                ('lastName', models.TextField(max_length=200)),
                ('status', models.BooleanField()),
                ('specialty', models.TextField(max_length=200)),
                ('location', models.TextField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workercompany', to='api.company')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.TimeField()),
                ('checkOut', models.TimeField()),
                ('date', models.DateField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchdog', to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulseMin', models.IntegerField()),
                ('pulseMax', models.IntegerField()),
                ('date', models.DateField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse', to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulseLast', models.IntegerField()),
                ('pulseMin', models.IntegerField()),
                ('pulseMax', models.IntegerField()),
                ('state', models.TextField(max_length=200)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='api.worker')),
            ],
        ),
    ]
