# Generated by Django 3.1.2 on 2020-10-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201029_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='time',
            field=models.TimeField(default='00:24'),
            preserve_default=False,
        ),
    ]
